services:
  - type: web
    name: helpdesk-backend
    env: python
    plan: free
    buildCommand: "cd helpdesk && pip install -r requirements.txt && python manage.py migrate"
    startCommand: "cd helpdesk && python manage.py runserver 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: helpdesk-1afn.onrender.com,localhost,127.0.0.1
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_ORIGIN
        value: https://your-frontend-url.vercel.app
