# Generated by Django 5.0.7 on 2025-10-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_comment_parent_ticket_due_at_ticket_priority_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketevent",
            name="actor",
        ),
        migrations.RemoveField(
            model_name="ticketevent",
            name="ticket",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="due_at",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="sla_hours",
        ),
        migrations.DeleteModel(
            name="IdempotencyRecord",
        ),
        migrations.DeleteModel(
            name="TicketEvent",
        ),
    ]
